# Generated by Django 6.1 on 2026-08-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграмм chat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграмм chat-id",
            ),
        ),
    ]
