# Generated by Django 6.1 on 2026-08-14 12:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место выполнения привычки", max_length=150, verbose_name="Место"
                    ),
                ),
                ("time", models.TimeField(help_text="Укажите время выполнения", verbose_name="Время")),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие для выполнения", max_length=250, verbose_name="Действие"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, help_text="Укажите наличие приятно привычки", verbose_name="Приятная"
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите периодичность выполнения",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите награду за выполнение",
                        max_length=250,
                        null=True,
                        verbose_name="Награда",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Укажите время выполнения привычки.", verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, help_text="Укажите публичность", verbose_name="Публичная"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_habits",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите создателя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("place",),
            },
        ),
    ]
