# Generated by Django 6.1 on 2026-08-14 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                help_text="Укажите время выполнения привычки.",
                validators=[django.core.validators.MaxValueValidator(2)],
                verbose_name="Время на выполнение (мин)",
            ),
        ),
    ]
