# Generated by Django 6.1 on 2026-08-14 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                help_text="Укажите время выполнения привычки.",
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="Время на выполнение (сек.)",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Укажите периодичность выполнения",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)],
                verbose_name="Периодичность",
            ),
        ),
    ]
