# Generated by Django 6.1 on 2026-08-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите связанную привычку",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
