# Generated by Django 6.1 on 2026-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="next_reminder",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите время следующего выполнения",
                null=True,
                verbose_name="Время следующего выполнения",
            ),
        ),
    ]
