# Generated by Django 6.1 on 2026-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_habit_next_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="reminder_10_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Укажите время напоминания",
                null=True,
                verbose_name="Время напоминания о выполнении",
            ),
        ),
    ]
